### ISSUE TITLE
Bracket not available on Alibaba anymore

### ISSUE THREAD

**Issue by Positron00** [jess-moss/moss-robot-arms#1]
Hi,

The Bracket Set in the parts list links to an Alibaba page that says it's no longer available. Do you have an alternative source for them? Thanks!

Bracket Set	18	$3	[Alibaba](https://www.alibaba.com/product-detail/STS3215-Metal-brackets-for-FEETECH-7_1600836829515.html)

**Comment by jess-moss** [comment]
Hello! Yes, unfortunately, this week is a Chinese national holiday, so the Feetech team is out of office, but as soon as they are back next week, I will provide an alternate link. Apologies for the delay.

**Comment by jess-moss** [comment]
Hello They are available again. Sorry about any confusion!
