### ISSUE TITLE
Assembly Video Not Linked

### ISSUE THREAD

**Issue by RonanKMcGovern** [jess-moss/moss-robot-arms#2]
Thanks for putting this repo together.

I notice the assembly video isn't linked yet. Perhaps it has not yet been made?

**Comment by jess-moss** [comment]
Hello! Yes, I am putting it together now! Sorry for the delay-- will be up by end of this week or next at the latest!

**Comment by RonanKMcGovern** [comment]
Cool beans

**Comment by jess-moss** [comment]
Assembly video now linked. Sorry for the delay! Thank you!
